#include <stdio.h>
int main()
  {
    printf("ANNABEL LEE\n");
    printf("BY EDGAR ALLAN POE\n");
    printf("\n");
    printf("It was many and many a year ago,\n");
    printf("  In a kingdom by the sea,\n");
    printf("That a maiden there lived whom you may know\n");
    printf("  By the name of Annabel Lee;\n");
    printf("And this maiden she lived with no other thought\n");
    printf("  Than to love and be loved by me.\n");
    printf("\n");
    printf("I was a child and she was a child,\n");
    printf("  In this kingdom by the sea,\n");
    printf("But we loved with a love that was more than love--\n");
    printf("  I and my Annabel Lee--\n");
    printf("With a love that the winged seraphs of Heaven\n");
    printf("  Coveted her and me.\n");
    printf("\n");
    printf("And this was the reason that, long ago,\n");
    printf("  In this kingdom by the sea,\n");
    printf("A wind blew out of a cloud, chilling\n");
    printf("  My beautiful Annabel Lee;\n");
    printf("So that her highborn kinsmen came\n");
    printf("  And bore her away from me,\n");
    printf("To shut her up in a sepulchre\n");
    printf("  In this kingdom by the sea.\n");
    printf("\n");
    printf("The angels, not half so happy in Heaven,\n");
    printf("  Went envying her and me--\n");
    printf("Yes!--that was the reason (as all men know,\n");
    printf("  In this kingdom by the sea)\n");
    printf("That the wind came out of the cloud by night,\n");
    printf("  Chilling and killing my Annabel Lee.\n");
    printf("\n");
    printf("But our love it was stronger by far than the love\n");
    printf("  Of those who were older than we--\n");
    printf("  Of many far wiser than we--\n");
    printf("And neither the angels in Heaven above\n");
    printf("  Nor the demons down under the sea\n");
    printf("Can ever dissever my soul from the soul\n");
    printf("  Of the beautiful Annabel Lee;\n");
    printf("\n");
    printf("For the moon never beams, without bringing me dreams\n");
    printf("  Of the beautiful Annabel Lee;\n");
    printf("And the stars never rise, but I feel the bright eyes\n");
    printf("  Of the beautiful Annabel Lee;\n");
    printf("And so, all the night-tide, I lie down by the side\n");
    printf("  Of my darling--my darling--my life and my bride,\n");
    printf("  In her sepulchre there by the sea--\n");
    printf("  In her tomb by the sounding sea.\n");
    return 0;
  }
